services:
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app
  app:
    build:
      context: ./app
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    networks:
      - app
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:9.1.0
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:

networks:
  app:
    driver: bridge

